<?php

namespace App\Support;

class CmsSectionBlueprint
{
    public static function find(string $pageSlug, string $editorSlug): ?array
    {
        foreach (self::all() as $blueprint) {
            if ($blueprint['page_slug'] === $pageSlug && $blueprint['editor_slug'] === $editorSlug) {
                return $blueprint;
            }
        }

        return null;
    }

    public static function all(): array
    {
        return [
            [
                'page_slug' => 'home',
                'editor_slug' => 'sliders',
                'page_label' => 'Home',
                'title' => 'Sliders principales',
                'description' => 'Administra las imágenes o videos del slider principal y su texto destacado.',
                'section_key' => 'hero',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'multiple',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título principal', 'type' => 'richtext'],
                    ['key' => 'description', 'label' => 'Descripción', 'type' => 'textarea'],
                ],
                'meta_fields' => [
                    ['key' => 'button_text', 'label' => 'Texto del botón', 'type' => 'text'],
                    ['key' => 'button_url', 'label' => 'Enlace del botón', 'type' => 'text'],
                ],
            ],
            [
                'page_slug' => 'home',
                'editor_slug' => 'banner',
                'page_label' => 'Home',
                'title' => 'Banner intermedio',
                'description' => 'Bloque visual que aparece entre los módulos del inicio.',
                'section_key' => 'hero_banner',
                'section_defaults' => ['order' => 'B'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'fields' => [
                    ['key' => 'subtitle', 'label' => 'Texto superior', 'type' => 'text'],
                    ['key' => 'title', 'label' => 'Título', 'type' => 'text'],
                    ['key' => 'description', 'label' => 'Texto largo', 'type' => 'richtext'],
                ],
                'meta_fields' => [
                    ['key' => 'button_text', 'label' => 'Texto del botón', 'type' => 'text', 'default' => 'Consultar'],
                    ['key' => 'button_url', 'label' => 'Enlace del botón', 'type' => 'text', 'default' => '/contacto'],
                ],
            ],
            [
                'page_slug' => 'home',
                'editor_slug' => 'nosotros-home',
                'page_label' => 'Home',
                'title' => 'Nosotros en Home',
                'description' => 'Resumen corto de la empresa con métricas y botón.',
                'section_key' => 'about_preview',
                'section_defaults' => ['order' => 'C'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título', 'type' => 'richtext'],
                    ['key' => 'description', 'label' => 'Descripción', 'type' => 'richtext'],
                ],
                'meta_fields' => [
                    ['key' => 'description_extra', 'label' => 'Texto secundario', 'type' => 'richtext'],
                    ['key' => 'years', 'label' => 'Años de experiencia', 'type' => 'number'],
                    ['key' => 'clients', 'label' => 'Cantidad de clientes', 'type' => 'number'],
                    ['key' => 'projects', 'label' => 'Cantidad de proyectos', 'type' => 'number'],
                    ['key' => 'button_text', 'label' => 'Texto del botón', 'type' => 'text'],
                    ['key' => 'button_url', 'label' => 'Enlace del botón', 'type' => 'text'],
                ],
            ],
            [
                'page_slug' => 'nosotros',
                'editor_slug' => 'banner',
                'page_label' => 'Nosotros',
                'title' => 'Banner principal',
                'description' => 'Encabezado visual de la página Nosotros.',
                'section_key' => 'nosotros_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'nosotros',
                'editor_slug' => 'contenido',
                'page_label' => 'Nosotros',
                'title' => 'Contenido principal',
                'description' => 'Historia o presentación principal de la empresa.',
                'section_key' => 'nosotros_about',
                'section_defaults' => ['order' => 'B'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título', 'type' => 'text'],
                    ['key' => 'description', 'label' => 'Contenido', 'type' => 'richtext'],
                ],
                'meta_fields' => [
                    ['key' => 'mission_title', 'label' => 'Título de misión', 'type' => 'text'],
                    ['key' => 'mission_description', 'label' => 'Contenido de misión', 'type' => 'richtext'],
                    ['key' => 'vision_title', 'label' => 'Título de visión', 'type' => 'text'],
                    ['key' => 'vision_description', 'label' => 'Contenido de visión', 'type' => 'richtext'],
                    ['key' => 'values_title', 'label' => 'Título de valores', 'type' => 'text'],
                    ['key' => 'values_description', 'label' => 'Contenido de valores', 'type' => 'richtext'],
                ],
            ],
            [
                'page_slug' => 'servicios',
                'editor_slug' => 'banner',
                'page_label' => 'Servicios',
                'title' => 'Banner de Servicios',
                'description' => 'Encabezado de la página de servicios.',
                'section_key' => 'servicios_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'equipos',
                'editor_slug' => 'banner',
                'page_label' => 'Equipos',
                'title' => 'Banner de Equipos',
                'description' => 'Encabezado de la página de equipos.',
                'section_key' => 'equipos_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'trabajos-realizados',
                'editor_slug' => 'banner',
                'page_label' => 'Trabajos realizados',
                'title' => 'Banner de Trabajos realizados',
                'description' => 'Encabezado de la página de trabajos realizados.',
                'section_key' => 'trabajos_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'normas',
                'editor_slug' => 'banner',
                'page_label' => 'Normas',
                'title' => 'Banner de Normas',
                'description' => 'Encabezado de la página de normas.',
                'section_key' => 'normas_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'normas',
                'editor_slug' => 'contenido',
                'page_label' => 'Normas',
                'title' => 'Contenido de Normas',
                'description' => 'Texto principal, imagen destacada y logos de certificaciones.',
                'section_key' => 'normas_content',
                'section_defaults' => ['order' => 'B'],
                'show_page_settings' => false,
                'media_mode' => 'multiple',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título', 'type' => 'text'],
                    ['key' => 'description', 'label' => 'Contenido', 'type' => 'richtext'],
                ],
                'meta_fields' => [
                    ['key' => 'button_text', 'label' => 'Texto del botón', 'type' => 'text'],
                    ['key' => 'button_url', 'label' => 'Enlace del botón', 'type' => 'text'],
                ],
            ],
            [
                'page_slug' => 'clientes',
                'editor_slug' => 'banner',
                'page_label' => 'Clientes',
                'title' => 'Banner de Clientes',
                'description' => 'Encabezado de la página de clientes.',
                'section_key' => 'clientes_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'clientes',
                'editor_slug' => 'contenido',
                'page_label' => 'Clientes',
                'title' => 'Contenido de Clientes',
                'description' => 'Texto principal del bloque antes de los rubros o tipos de cliente.',
                'section_key' => 'clientes_content',
                'section_defaults' => ['order' => 'B'],
                'show_page_settings' => false,
                'media_mode' => 'none',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título', 'type' => 'text'],
                ],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'contacto',
                'editor_slug' => 'banner',
                'page_label' => 'Contacto',
                'title' => 'Banner de Contacto',
                'description' => 'Encabezado de la página de contacto.',
                'section_key' => 'contacto_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'contacto',
                'editor_slug' => 'formulario',
                'page_label' => 'Contacto',
                'title' => 'Formulario y datos de contacto',
                'description' => 'Textos del formulario, emails y teléfonos visibles para el usuario.',
                'section_key' => 'contacto_content',
                'section_defaults' => ['order' => 'B'],
                'show_page_settings' => false,
                'media_mode' => 'none',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título del formulario', 'type' => 'text'],
                ],
                'meta_fields' => [
                    ['key' => 'email_title', 'label' => 'Título del bloque email', 'type' => 'text'],
                    ['key' => 'phone_title', 'label' => 'Título del bloque teléfono', 'type' => 'text'],
                    ['key' => 'first_name_label', 'label' => 'Label nombre', 'type' => 'text'],
                    ['key' => 'last_name_label', 'label' => 'Label apellido', 'type' => 'text'],
                    ['key' => 'email_label', 'label' => 'Label email', 'type' => 'text'],
                    ['key' => 'phone_label', 'label' => 'Label teléfono', 'type' => 'text'],
                    ['key' => 'message_label', 'label' => 'Label mensaje', 'type' => 'text'],
                    ['key' => 'button_text', 'label' => 'Texto del botón', 'type' => 'text'],
                    ['key' => 'contact_emails', 'label' => 'Emails de contacto', 'type' => 'list', 'help' => 'Escribe un email por línea.'],
                    ['key' => 'contact_phones', 'label' => 'Teléfonos de contacto', 'type' => 'phone_list', 'help' => 'Usa una línea por teléfono. Formato: Etiqueta | Número'],
                ],
            ],
            [
                'page_slug' => 'presupuesto',
                'editor_slug' => 'banner',
                'page_label' => 'Presupuesto',
                'title' => 'Banner de Presupuesto',
                'description' => 'Encabezado de la página de presupuesto.',
                'section_key' => 'presupuesto_banner',
                'section_defaults' => ['order' => 'A'],
                'show_page_settings' => false,
                'media_mode' => 'single',
                'hide_section_order' => true,
                'image_only_media' => true,
                'fields' => [],
                'meta_fields' => [],
            ],
            [
                'page_slug' => 'presupuesto',
                'editor_slug' => 'formulario',
                'page_label' => 'Presupuesto',
                'title' => 'Formulario de Presupuesto',
                'description' => 'Textos del formulario y opciones visibles al usuario.',
                'section_key' => 'presupuesto_content',
                'section_defaults' => ['order' => 'B'],
                'show_page_settings' => false,
                'media_mode' => 'none',
                'fields' => [
                    ['key' => 'title', 'label' => 'Título bloque de contacto', 'type' => 'text'],
                    ['key' => 'subtitle', 'label' => 'Título bloque de consulta', 'type' => 'text'],
                ],
                'meta_fields' => [
                    ['key' => 'name_label', 'label' => 'Label nombre', 'type' => 'text'],
                    ['key' => 'last_name_label', 'label' => 'Label apellido', 'type' => 'text'],
                    ['key' => 'email_label', 'label' => 'Label email', 'type' => 'text'],
                    ['key' => 'phone_label', 'label' => 'Label teléfono', 'type' => 'text'],
                    ['key' => 'message_label', 'label' => 'Label mensaje', 'type' => 'text'],
                    ['key' => 'service_label', 'label' => 'Label selector servicios', 'type' => 'text'],
                    ['key' => 'equipment_label', 'label' => 'Label selector equipos', 'type' => 'text'],
                    ['key' => 'button_text', 'label' => 'Texto del botón', 'type' => 'text'],
                ],
            ],
        ];
    }
}
